name: emlak_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  image_picker: ^1.0.4
  mime: ^1.0.4
  path: ^1.8.3
  http: ^0.13.6
  intl:
  geocoding:
  google_maps_flutter:
  carousel_slider:
  flutter_dotenv:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Italic.ttf
        - asset: assets/fonts/NotoSerif-Regular.ttf
          style: italic
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

